version: '3.6'

services:
  bookworms-club-backend:
    image: bookworms-club-backend
    build:
      context: ./
    container_name: bookworms_club_backend
    env_file:
      - env_file
    expose:
      - ${PORT-4000}
    ports:
      - '4000:${PORT-4000}'
    depends_on:
      - bookworms-club-mongodb
    restart: on-failure
    stop_grace_period: 5s

  bookworms-club-mongodb:
    image: mongo:bionic
    container_name: bookworms_club_mongodb
    ports:
      - 27017:27017
    expose:
      - 27017

networks:
  default:
    external:
      name: nginx-proxy
